// AUTO-GENERATED by scripts/gen-api-stubs.ts — DO NOT EDIT BY HAND.
// Source: @codingame/monaco-vscode-api/vscode-dts/vscode.d.ts
//
// This file emits stubs for every documented vscode API surface
// that api-shim.ts does NOT already implement. Real implementations
// in api-shim.ts win because we spread `vscodeStubs` BEFORE the
// real api object — last-write wins.
//
// Re-generate after vscode.d.ts updates:
//   npx tsc scripts/gen-api-stubs.ts --target es2020 --module commonjs --outDir scripts/dist && node scripts/dist/gen-api-stubs.js
/* eslint-disable @typescript-eslint/no-explicit-any */

/** No-op marker — extensions calling auto-stubbed methods get this back
 * instead of crashing. We log on first call to surface what we still
 * need to implement for real. */
const _autoStubReported = new Set<string>();
function autoStub(name: string): any {
  return (...args: any[]) => {
    if (!_autoStubReported.has(name)) {
      _autoStubReported.add(name);
      try { process.stderr.write(`[api-shim] auto-stub called: ${name} (${args.length} arg${args.length === 1 ? '' : 's'})\n`); } catch {}
    }
    return undefined;
  };
}
function autoStubAsync(name: string): any {
  const sync = autoStub(name);
  return (...args: any[]) => Promise.resolve(sync(...args));
}

export const TextEditorSelectionChangeKind = Object.freeze({
  Keyboard: 1,
  Mouse: 2,
  Command: 3,
});

export const TextEditorLineNumbersStyle = Object.freeze({
  Off: 0,
  On: 1,
  Relative: 2,
  Interval: 3,
});

export const EndOfLine = Object.freeze({
  LF: 1,
  CRLF: 2,
});

export const QuickPickItemKind = Object.freeze({
  Separator: -1,
  Default: 0,
});

export const InputBoxValidationSeverity = Object.freeze({
  Info: 1,
  Warning: 2,
  Error: 3,
});

export const CodeActionTriggerKind = Object.freeze({
  Invoke: 1,
  Automatic: 2,
});

export const DocumentHighlightKind = Object.freeze({
  Text: 0,
  Read: 1,
  Write: 2,
});

export const SymbolTag = Object.freeze({
  Deprecated: 1,
});

export const SignatureHelpTriggerKind = Object.freeze({
  Invoke: 1,
  TriggerCharacter: 2,
  ContentChange: 3,
});

export const CompletionItemTag = Object.freeze({
  Deprecated: 1,
});

export const CompletionTriggerKind = Object.freeze({
  Invoke: 0,
  TriggerCharacter: 1,
  TriggerForIncompleteCompletions: 2,
});

export const InlineCompletionTriggerKind = Object.freeze({
  Invoke: 0,
  Automatic: 1,
});

export const InlayHintKind = Object.freeze({
  Type: 1,
  Parameter: 2,
});

export const FoldingRangeKind = Object.freeze({
  Comment: 1,
  Imports: 2,
  Region: 3,
});

export const DocumentPasteTriggerKind = Object.freeze({
  Automatic: 0,
  PasteAs: 1,
});

export const IndentAction = Object.freeze({
  None: 0,
  Indent: 1,
  IndentOutdent: 2,
  Outdent: 3,
});

export const SyntaxTokenType = Object.freeze({
  Other: 0,
  Comment: 1,
  String: 2,
  RegEx: 3,
});

export const DiagnosticTag = Object.freeze({
  Unnecessary: 1,
  Deprecated: 2,
});

export const LanguageStatusSeverity = Object.freeze({
  Information: 0,
  Warning: 1,
  Error: 2,
});

export const TerminalLocation = Object.freeze({
  Panel: 1,
  Editor: 2,
});

export const TerminalShellExecutionCommandLineConfidence = Object.freeze({
  Low: 0,
  Medium: 1,
  High: 2,
});

export const ColorThemeKind = Object.freeze({
  Light: 1,
  Dark: 2,
  HighContrast: 3,
  HighContrastLight: 4,
});

export const TaskRevealKind = Object.freeze({
  Always: 1,
  Silent: 2,
  Never: 3,
});

export const TaskPanelKind = Object.freeze({
  Shared: 1,
  Dedicated: 2,
  New: 3,
});

export const ShellQuoting = Object.freeze({
  Escape: 1,
  Strong: 2,
  Weak: 3,
});

export const TaskScope = Object.freeze({
  Global: 1,
  Workspace: 2,
});

export const FilePermission = Object.freeze({
  Readonly: 1,
});

export const TreeItemCheckboxState = Object.freeze({
  Unchecked: 0,
  Checked: 1,
});

export const TerminalExitReason = Object.freeze({
  Unknown: 0,
  Shutdown: 1,
  Process: 2,
  User: 3,
  Extension: 4,
});

export const EnvironmentVariableMutatorType = Object.freeze({
  Replace: 1,
  Append: 2,
  Prepend: 3,
});

export const ProgressLocation = Object.freeze({
  SourceControl: 1,
  Window: 10,
  Notification: 15,
});

export const QuickInputButtonLocation = Object.freeze({
  Title: 1,
  Inline: 2,
  Input: 3,
});

export const TextDocumentChangeReason = Object.freeze({
  Undo: 1,
  Redo: 2,
});

export const TextDocumentSaveReason = Object.freeze({
  Manual: 1,
  AfterDelay: 2,
  FocusOut: 3,
});

export const NotebookEditorRevealType = Object.freeze({
  Default: 0,
  InCenter: 1,
  InCenterIfOutsideViewport: 2,
  AtTop: 3,
});

export const NotebookCellKind = Object.freeze({
  Markup: 1,
  Code: 2,
});

export const NotebookControllerAffinity = Object.freeze({
  Default: 1,
  Preferred: 2,
});

export const NotebookCellStatusBarAlignment = Object.freeze({
  Left: 1,
  Right: 2,
});

export const DebugConfigurationProviderTriggerKind = Object.freeze({
  Initial: 1,
  Dynamic: 2,
});

export const CommentThreadCollapsibleState = Object.freeze({
  Collapsed: 0,
  Expanded: 1,
});

export const CommentMode = Object.freeze({
  Editing: 0,
  Preview: 1,
});

export const CommentThreadState = Object.freeze({
  Unresolved: 0,
  Resolved: 1,
});

export const TestRunProfileKind = Object.freeze({
  Run: 1,
  Debug: 2,
  Coverage: 3,
});

export const ChatResultFeedbackKind = Object.freeze({
  Unhelpful: 0,
  Helpful: 1,
});

export const LanguageModelChatMessageRole = Object.freeze({
  User: 1,
  Assistant: 2,
});

export const LanguageModelChatToolMode = Object.freeze({
  Auto: 1,
  Required: 2,
});

export class CancellationTokenSource {
  constructor() {
  }
}

export class CancellationError {
  constructor() {
  }
}

export class CodeLens {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class EvaluatableExpression {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class InlineValueText {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class InlineValueVariableLookup {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class InlineValueEvaluatableExpression {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class DocumentHighlight {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class SnippetTextEdit {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class NotebookEdit {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class SemanticTokensLegend {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class SemanticTokensBuilder {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class SemanticTokens {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class SemanticTokensEdits {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class SemanticTokensEdit {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class ParameterInformation {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class SignatureInformation {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class SignatureHelp {
  constructor() {
  }
}

export class CompletionItem {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class CompletionList {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class InlineCompletionList {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class InlineCompletionItem {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class DocumentLink {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class Color {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
  }
}

export class ColorInformation {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class ColorPresentation {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class InlayHintLabelPart {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class InlayHint {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class FoldingRange {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class SelectionRange {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class CallHierarchyItem {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any, arg4: any, arg5: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
    (this as any)[`_arg4`] = arg4;
    (this as any)[`_arg5`] = arg5;
  }
}

export class CallHierarchyIncomingCall {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class CallHierarchyOutgoingCall {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class TypeHierarchyItem {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any, arg4: any, arg5: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
    (this as any)[`_arg4`] = arg4;
    (this as any)[`_arg5`] = arg5;
  }
}

export class LinkedEditingRanges {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class DocumentDropOrPasteEditKind {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class DocumentDropEdit {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class DocumentPasteEdit {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class Location {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class DiagnosticRelatedInformation {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class TerminalLink {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class TerminalProfile {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class FileDecoration {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class TaskGroup {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class ProcessExecution {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class ShellExecution {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class CustomExecution {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class Task {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any, arg4: any, arg5: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
    (this as any)[`_arg4`] = arg4;
    (this as any)[`_arg5`] = arg5;
  }
}

export class DataTransferItem {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class DataTransfer {
  constructor() {
  }
}

export class TreeItem {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class QuickInputButtons {
  constructor() {
  }
}

export class NotebookRange {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class NotebookCellData {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class NotebookData {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class NotebookCellStatusBarItem {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class Breakpoint {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
  }
}

export class DebugThread {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class DebugStackFrame {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class TestTag {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class TestRunRequest {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any, arg4: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
    (this as any)[`_arg4`] = arg4;
  }
}

export class TestMessageStackFrame {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class TestMessage {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class TestCoverageCount {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class FileCoverage {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any, arg4: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
    (this as any)[`_arg4`] = arg4;
  }
}

export class StatementCoverage {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class BranchCoverage {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class DeclarationCoverage {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class TelemetryTrustedValue {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class ChatRequestTurn {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any, arg4: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
    (this as any)[`_arg4`] = arg4;
  }
}

export class ChatResponseTurn {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class ChatResponseMarkdownPart {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class ChatResponseFileTreePart {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class ChatResponseAnchorPart {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class ChatResponseProgressPart {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class ChatResponseReferencePart {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class ChatResponseCommandButtonPart {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class LanguageModelChatMessage {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class LanguageModelError {
  constructor() {
  }
}

export class McpStdioServerDefinition {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any, arg4: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
    (this as any)[`_arg4`] = arg4;
  }
}

export class McpHttpServerDefinition {
  constructor(arg0: any, arg1: any, arg2: any, arg3: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
    (this as any)[`_arg3`] = arg3;
  }
}

export class LanguageModelToolCallPart {
  constructor(arg0: any, arg1: any, arg2: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
    (this as any)[`_arg2`] = arg2;
  }
}

export class LanguageModelToolResultPart {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export class LanguageModelTextPart {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class LanguageModelPromptTsxPart {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class LanguageModelToolResult {
  constructor(arg0: any) {
    (this as any)[`_arg0`] = arg0;
  }
}

export class LanguageModelDataPart {
  constructor(arg0: any, arg1: any) {
    (this as any)[`_arg0`] = arg0;
    (this as any)[`_arg1`] = arg1;
  }
}

export const _ns_tasks = {
  registerTaskProvider: autoStub("vscode.tasks.registerTaskProvider"),
  fetchTasks: autoStubAsync("vscode.tasks.fetchTasks"),
  executeTask: autoStubAsync("vscode.tasks.executeTask"),
  taskExecutions: undefined as any,
  onDidStartTask: undefined as any,
  onDidEndTask: undefined as any,
  onDidStartTaskProcess: undefined as any,
  onDidEndTaskProcess: undefined as any,
};

export const _ns_env = {
  createTelemetryLogger: autoStub("vscode.env.createTelemetryLogger"),
  openExternal: autoStubAsync("vscode.env.openExternal"),
  asExternalUri: autoStubAsync("vscode.env.asExternalUri"),
  appName: undefined as any,
  appRoot: undefined as any,
  appHost: undefined as any,
  uriScheme: undefined as any,
  language: undefined as any,
  clipboard: undefined as any,
  machineId: undefined as any,
  sessionId: undefined as any,
  isNewAppInstall: undefined as any,
  isAppPortable: undefined as any,
  isTelemetryEnabled: undefined as any,
  onDidChangeTelemetryEnabled: undefined as any,
  onDidChangeShell: undefined as any,
  remoteName: undefined as any,
  shell: undefined as any,
  uiKind: undefined as any,
  logLevel: undefined as any,
  onDidChangeLogLevel: undefined as any,
};

export const _ns_commands = {
  registerCommand: autoStub("vscode.commands.registerCommand"),
  registerTextEditorCommand: autoStub("vscode.commands.registerTextEditorCommand"),
  executeCommand: autoStubAsync("vscode.commands.executeCommand"),
  getCommands: autoStubAsync("vscode.commands.getCommands"),
};

export const _ns_window = {
  showTextDocument: autoStubAsync("vscode.window.showTextDocument"),
  showNotebookDocument: autoStubAsync("vscode.window.showNotebookDocument"),
  createTextEditorDecorationType: autoStub("vscode.window.createTextEditorDecorationType"),
  showInformationMessage: autoStubAsync("vscode.window.showInformationMessage"),
  showWarningMessage: autoStubAsync("vscode.window.showWarningMessage"),
  showErrorMessage: autoStubAsync("vscode.window.showErrorMessage"),
  showQuickPick: autoStubAsync("vscode.window.showQuickPick"),
  showWorkspaceFolderPick: autoStubAsync("vscode.window.showWorkspaceFolderPick"),
  showOpenDialog: autoStubAsync("vscode.window.showOpenDialog"),
  showSaveDialog: autoStubAsync("vscode.window.showSaveDialog"),
  showInputBox: autoStubAsync("vscode.window.showInputBox"),
  createQuickPick: autoStub("vscode.window.createQuickPick"),
  createInputBox: autoStub("vscode.window.createInputBox"),
  createOutputChannel: autoStub("vscode.window.createOutputChannel"),
  createWebviewPanel: autoStub("vscode.window.createWebviewPanel"),
  setStatusBarMessage: autoStub("vscode.window.setStatusBarMessage"),
  withScmProgress: autoStubAsync("vscode.window.withScmProgress"),
  withProgress: autoStubAsync("vscode.window.withProgress"),
  createStatusBarItem: autoStub("vscode.window.createStatusBarItem"),
  createTerminal: autoStub("vscode.window.createTerminal"),
  registerTreeDataProvider: autoStub("vscode.window.registerTreeDataProvider"),
  createTreeView: autoStub("vscode.window.createTreeView"),
  registerUriHandler: autoStub("vscode.window.registerUriHandler"),
  registerWebviewPanelSerializer: autoStub("vscode.window.registerWebviewPanelSerializer"),
  registerWebviewViewProvider: autoStub("vscode.window.registerWebviewViewProvider"),
  registerCustomEditorProvider: autoStub("vscode.window.registerCustomEditorProvider"),
  registerTerminalLinkProvider: autoStub("vscode.window.registerTerminalLinkProvider"),
  registerTerminalProfileProvider: autoStub("vscode.window.registerTerminalProfileProvider"),
  registerFileDecorationProvider: autoStub("vscode.window.registerFileDecorationProvider"),
  tabGroups: undefined as any,
  activeTextEditor: undefined as any,
  visibleTextEditors: undefined as any,
  onDidChangeActiveTextEditor: undefined as any,
  onDidChangeVisibleTextEditors: undefined as any,
  onDidChangeTextEditorSelection: undefined as any,
  onDidChangeTextEditorVisibleRanges: undefined as any,
  onDidChangeTextEditorOptions: undefined as any,
  onDidChangeTextEditorViewColumn: undefined as any,
  visibleNotebookEditors: undefined as any,
  onDidChangeVisibleNotebookEditors: undefined as any,
  activeNotebookEditor: undefined as any,
  onDidChangeActiveNotebookEditor: undefined as any,
  onDidChangeNotebookEditorSelection: undefined as any,
  onDidChangeNotebookEditorVisibleRanges: undefined as any,
  terminals: undefined as any,
  activeTerminal: undefined as any,
  onDidChangeActiveTerminal: undefined as any,
  onDidOpenTerminal: undefined as any,
  onDidCloseTerminal: undefined as any,
  onDidChangeTerminalState: undefined as any,
  onDidChangeTerminalShellIntegration: undefined as any,
  onDidStartTerminalShellExecution: undefined as any,
  onDidEndTerminalShellExecution: undefined as any,
  state: undefined as any,
  onDidChangeWindowState: undefined as any,
  activeColorTheme: undefined as any,
  onDidChangeActiveColorTheme: undefined as any,
};

export const _ns_workspace = {
  getWorkspaceFolder: autoStub("vscode.workspace.getWorkspaceFolder"),
  asRelativePath: autoStub("vscode.workspace.asRelativePath"),
  updateWorkspaceFolders: autoStub("vscode.workspace.updateWorkspaceFolders"),
  createFileSystemWatcher: autoStub("vscode.workspace.createFileSystemWatcher"),
  findFiles: autoStubAsync("vscode.workspace.findFiles"),
  save: autoStubAsync("vscode.workspace.save"),
  saveAs: autoStubAsync("vscode.workspace.saveAs"),
  saveAll: autoStubAsync("vscode.workspace.saveAll"),
  applyEdit: autoStubAsync("vscode.workspace.applyEdit"),
  openTextDocument: autoStubAsync("vscode.workspace.openTextDocument"),
  registerTextDocumentContentProvider: autoStub("vscode.workspace.registerTextDocumentContentProvider"),
  openNotebookDocument: autoStubAsync("vscode.workspace.openNotebookDocument"),
  registerNotebookSerializer: autoStub("vscode.workspace.registerNotebookSerializer"),
  getConfiguration: autoStub("vscode.workspace.getConfiguration"),
  registerTaskProvider: autoStub("vscode.workspace.registerTaskProvider"),
  registerFileSystemProvider: autoStub("vscode.workspace.registerFileSystemProvider"),
  decode: autoStubAsync("vscode.workspace.decode"),
  encode: autoStubAsync("vscode.workspace.encode"),
  fs: undefined as any,
  rootPath: undefined as any,
  workspaceFolders: undefined as any,
  name: undefined as any,
  workspaceFile: undefined as any,
  onDidChangeWorkspaceFolders: undefined as any,
  textDocuments: undefined as any,
  onDidOpenTextDocument: undefined as any,
  onDidCloseTextDocument: undefined as any,
  onDidChangeTextDocument: undefined as any,
  onWillSaveTextDocument: undefined as any,
  onDidSaveTextDocument: undefined as any,
  notebookDocuments: undefined as any,
  onDidChangeNotebookDocument: undefined as any,
  onWillSaveNotebookDocument: undefined as any,
  onDidSaveNotebookDocument: undefined as any,
  onDidOpenNotebookDocument: undefined as any,
  onDidCloseNotebookDocument: undefined as any,
  onWillCreateFiles: undefined as any,
  onDidCreateFiles: undefined as any,
  onWillDeleteFiles: undefined as any,
  onDidDeleteFiles: undefined as any,
  onWillRenameFiles: undefined as any,
  onDidRenameFiles: undefined as any,
  onDidChangeConfiguration: undefined as any,
  isTrusted: undefined as any,
  onDidGrantWorkspaceTrust: undefined as any,
};

export const _ns_languages = {
  getLanguages: autoStubAsync("vscode.languages.getLanguages"),
  setTextDocumentLanguage: autoStubAsync("vscode.languages.setTextDocumentLanguage"),
  match: autoStub("vscode.languages.match"),
  getDiagnostics: autoStub("vscode.languages.getDiagnostics"),
  createDiagnosticCollection: autoStub("vscode.languages.createDiagnosticCollection"),
  createLanguageStatusItem: autoStub("vscode.languages.createLanguageStatusItem"),
  registerCompletionItemProvider: autoStub("vscode.languages.registerCompletionItemProvider"),
  registerInlineCompletionItemProvider: autoStub("vscode.languages.registerInlineCompletionItemProvider"),
  registerCodeActionsProvider: autoStub("vscode.languages.registerCodeActionsProvider"),
  registerCodeLensProvider: autoStub("vscode.languages.registerCodeLensProvider"),
  registerDefinitionProvider: autoStub("vscode.languages.registerDefinitionProvider"),
  registerImplementationProvider: autoStub("vscode.languages.registerImplementationProvider"),
  registerTypeDefinitionProvider: autoStub("vscode.languages.registerTypeDefinitionProvider"),
  registerDeclarationProvider: autoStub("vscode.languages.registerDeclarationProvider"),
  registerHoverProvider: autoStub("vscode.languages.registerHoverProvider"),
  registerEvaluatableExpressionProvider: autoStub("vscode.languages.registerEvaluatableExpressionProvider"),
  registerInlineValuesProvider: autoStub("vscode.languages.registerInlineValuesProvider"),
  registerDocumentHighlightProvider: autoStub("vscode.languages.registerDocumentHighlightProvider"),
  registerDocumentSymbolProvider: autoStub("vscode.languages.registerDocumentSymbolProvider"),
  registerWorkspaceSymbolProvider: autoStub("vscode.languages.registerWorkspaceSymbolProvider"),
  registerReferenceProvider: autoStub("vscode.languages.registerReferenceProvider"),
  registerRenameProvider: autoStub("vscode.languages.registerRenameProvider"),
  registerDocumentSemanticTokensProvider: autoStub("vscode.languages.registerDocumentSemanticTokensProvider"),
  registerDocumentRangeSemanticTokensProvider: autoStub("vscode.languages.registerDocumentRangeSemanticTokensProvider"),
  registerDocumentFormattingEditProvider: autoStub("vscode.languages.registerDocumentFormattingEditProvider"),
  registerDocumentRangeFormattingEditProvider: autoStub("vscode.languages.registerDocumentRangeFormattingEditProvider"),
  registerOnTypeFormattingEditProvider: autoStub("vscode.languages.registerOnTypeFormattingEditProvider"),
  registerSignatureHelpProvider: autoStub("vscode.languages.registerSignatureHelpProvider"),
  registerDocumentLinkProvider: autoStub("vscode.languages.registerDocumentLinkProvider"),
  registerColorProvider: autoStub("vscode.languages.registerColorProvider"),
  registerInlayHintsProvider: autoStub("vscode.languages.registerInlayHintsProvider"),
  registerFoldingRangeProvider: autoStub("vscode.languages.registerFoldingRangeProvider"),
  registerSelectionRangeProvider: autoStub("vscode.languages.registerSelectionRangeProvider"),
  registerCallHierarchyProvider: autoStub("vscode.languages.registerCallHierarchyProvider"),
  registerTypeHierarchyProvider: autoStub("vscode.languages.registerTypeHierarchyProvider"),
  registerLinkedEditingRangeProvider: autoStub("vscode.languages.registerLinkedEditingRangeProvider"),
  registerDocumentDropEditProvider: autoStub("vscode.languages.registerDocumentDropEditProvider"),
  registerDocumentPasteEditProvider: autoStub("vscode.languages.registerDocumentPasteEditProvider"),
  setLanguageConfiguration: autoStub("vscode.languages.setLanguageConfiguration"),
  onDidChangeDiagnostics: undefined as any,
};

export const _ns_notebooks = {
  createNotebookController: autoStub("vscode.notebooks.createNotebookController"),
  registerNotebookCellStatusBarItemProvider: autoStub("vscode.notebooks.registerNotebookCellStatusBarItemProvider"),
  createRendererMessaging: autoStub("vscode.notebooks.createRendererMessaging"),
};

export const _ns_scm = {
  createSourceControl: autoStub("vscode.scm.createSourceControl"),
  inputBox: undefined as any,
};

export const _ns_debug = {
  registerDebugConfigurationProvider: autoStub("vscode.debug.registerDebugConfigurationProvider"),
  registerDebugAdapterDescriptorFactory: autoStub("vscode.debug.registerDebugAdapterDescriptorFactory"),
  registerDebugAdapterTrackerFactory: autoStub("vscode.debug.registerDebugAdapterTrackerFactory"),
  startDebugging: autoStubAsync("vscode.debug.startDebugging"),
  stopDebugging: autoStubAsync("vscode.debug.stopDebugging"),
  addBreakpoints: autoStub("vscode.debug.addBreakpoints"),
  removeBreakpoints: autoStub("vscode.debug.removeBreakpoints"),
  asDebugSourceUri: autoStub("vscode.debug.asDebugSourceUri"),
  activeDebugSession: undefined as any,
  activeDebugConsole: undefined as any,
  breakpoints: undefined as any,
  onDidChangeActiveDebugSession: undefined as any,
  onDidStartDebugSession: undefined as any,
  onDidReceiveDebugSessionCustomEvent: undefined as any,
  onDidTerminateDebugSession: undefined as any,
  onDidChangeBreakpoints: undefined as any,
  activeStackItem: undefined as any,
  onDidChangeActiveStackItem: undefined as any,
};

export const _ns_extensions = {
  getExtension: autoStub("vscode.extensions.getExtension"),
  all: undefined as any,
  onDidChange: undefined as any,
};

export const _ns_comments = {
  createCommentController: autoStub("vscode.comments.createCommentController"),
};

export const _ns_authentication = {
  getSession: autoStubAsync("vscode.authentication.getSession"),
  getAccounts: autoStubAsync("vscode.authentication.getAccounts"),
  registerAuthenticationProvider: autoStub("vscode.authentication.registerAuthenticationProvider"),
  onDidChangeSessions: undefined as any,
};

export const _ns_l10n = {
  t: autoStub("vscode.l10n.t"),
  bundle: undefined as any,
  uri: undefined as any,
};

export const _ns_tests = {
  createTestController: autoStub("vscode.tests.createTestController"),
};

export const _ns_chat = {
  createChatParticipant: autoStub("vscode.chat.createChatParticipant"),
};

export const _ns_lm = {
  selectChatModels: autoStubAsync("vscode.lm.selectChatModels"),
  registerTool: autoStub("vscode.lm.registerTool"),
  invokeTool: autoStubAsync("vscode.lm.invokeTool"),
  registerMcpServerDefinitionProvider: autoStub("vscode.lm.registerMcpServerDefinitionProvider"),
  registerLanguageModelChatProvider: autoStub("vscode.lm.registerLanguageModelChatProvider"),
  onDidChangeChatModels: undefined as any,
  tools: undefined as any,
};

/** Roll-up of every auto-stubbed namespace.  api-shim.ts merges
 * its REAL namespace objects on top so real implementations win. */
export const _autoStubNamespaces = {
  tasks: _ns_tasks,
  env: _ns_env,
  commands: _ns_commands,
  window: _ns_window,
  workspace: _ns_workspace,
  languages: _ns_languages,
  notebooks: _ns_notebooks,
  scm: _ns_scm,
  debug: _ns_debug,
  extensions: _ns_extensions,
  comments: _ns_comments,
  authentication: _ns_authentication,
  l10n: _ns_l10n,
  tests: _ns_tests,
  chat: _ns_chat,
  lm: _ns_lm,
};
