// This module has been moved.
//
// Channel bridge Tauri commands are now generated by the channel_commands! macro
// in src/commands/channels.rs (crate::commands::channels::*).
//
// This file is intentionally empty — the `pub mod commands` declaration has been
// removed from engine/mod.rs. The file is kept only as a tombstone.
